# Milestone 1

## Task: Write a function which will compute the density at each lattice point.

We discretize a 2D domain so that the position vector r can be expressed through the two coordinates x and y

~ The first step is to identify the proper array representation of density ρ(x,y), velocity v(x,y) and function f(x,y,v)

~ The density is given by:
ρ(x,y)=∫dvf(x,y,v).

## Task: Write a function which will compute the density at each lattice point.

The velocity field v is given by v(x,y)=1ρ(x,y)∫dvf(x,y,v)⋅c(v).

Write a function which will compute the velocity field at your grid points.

Initialize the probability density function with values of your choice. We suggest you start with a grid that is 15 lattice points wide and 10 points long. Visualize the density and the components of the velocity field on your grid using the python library matplotlib.

Write a function streaming which shifts the components of the probability density function along the grid according to their direction. Hint: if you use numpy.roll this can achieved in a single command!

write a test that checks whether mass is conserved between two timesteps.


In [146]:
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [218]:
a = np.arange(150) #Make a 1D array of 150 indices
a.shape = (10,15) #Make the 1D array into a 10x15 2D array
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14],
       [ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104],
       [105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134],
       [135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
        148, 149]])

In [219]:
np.shape(a) #Confirm the shape

(10, 15)

In [220]:
a = np.dstack([a]*9) #Copy the 10x15 array 9 times in the z direction
a

array([[[  0,   0,   0, ...,   0,   0,   0],
        [  1,   1,   1, ...,   1,   1,   1],
        [  2,   2,   2, ...,   2,   2,   2],
        ...,
        [ 12,  12,  12, ...,  12,  12,  12],
        [ 13,  13,  13, ...,  13,  13,  13],
        [ 14,  14,  14, ...,  14,  14,  14]],

       [[ 15,  15,  15, ...,  15,  15,  15],
        [ 16,  16,  16, ...,  16,  16,  16],
        [ 17,  17,  17, ...,  17,  17,  17],
        ...,
        [ 27,  27,  27, ...,  27,  27,  27],
        [ 28,  28,  28, ...,  28,  28,  28],
        [ 29,  29,  29, ...,  29,  29,  29]],

       [[ 30,  30,  30, ...,  30,  30,  30],
        [ 31,  31,  31, ...,  31,  31,  31],
        [ 32,  32,  32, ...,  32,  32,  32],
        ...,
        [ 42,  42,  42, ...,  42,  42,  42],
        [ 43,  43,  43, ...,  43,  43,  43],
        [ 44,  44,  44, ...,  44,  44,  44]],

       ...,

       [[105, 105, 105, ..., 105, 105, 105],
        [106, 106, 106, ..., 106, 106, 106],
        [107, 107, 107, ..., 107, 107, 107

In [221]:
np.shape(a) #Confirm the shape

(10, 15, 9)

In [222]:
a[0,2,3] #Check the values

2

Numpy stores the array values as [y,x,z], where x is to the right, y is down, and z is back. However, when displaying an array, it is out put as [[x,z],y], where x is down and z is right within each cell, and y is down across all the cells.

In [236]:
#def streaming(shift_factor):
#    for i in range(np.size(a,axis=2)):
#        a[:,:,i]=np.roll(a[:,:,i],(0,shift_factor),axis=(0,1)) #Shift every row in the x axis by the shift_factor
#    return a

def streaming(shift_factor):
    #0:The nullth z plane does not get shifted as it represents the position
    a[:,:,1]=np.roll(a[:,:,1],(0,shift_factor),axis=(0,1)) #1:Shift every element in the first z plane in the x direction by the shift_factor
    a[:,:,2]=np.roll(a[:,:,2],(shift_factor,0),axis=(0,1)) #2:Shift every element in the second z plane in the y direction by the shift_factor
    a[:,:,3]=np.roll(a[:,:,3],(0,-shift_factor),axis=(0,1)) #3:Shift every element in the third z plane in the -x direction by the shift_factor
    a[:,:,4]=np.roll(a[:,:,4],(-shift_factor,0),axis=(0,1)) #4:Shift every element in the fourth z plane in the -y direction by the shift_factor
    a[:,:,5]=np.roll(a[:,:,5],(shift_factor,shift_factor),axis=(0,1)) #5:Shift every element in the fifth z plane in the x and y direction by the shift_factor
    a[:,:,6]=np.roll(a[:,:,6],(shift_factor,-shift_factor),axis=(0,1)) #6:Shift every element in the sixth z plane in the -x and y direction by the shift_factor
    a[:,:,7]=np.roll(a[:,:,7],(-shift_factor,-shift_factor),axis=(0,1)) #7:Shift every element in the seventh z plane in the -x and -y direction by the shift_factor
    a[:,:,8]=np.roll(a[:,:,8],(-shift_factor,shift_factor),axis=(0,1)) #8:Shift every element in the eighth z plane in the x and -y direction by the shift_factor
    
    return a

In [266]:
streaming(1)

array([[[  0,   0,   0, ...,   0,   0,   0],
        [  1,   1,   1, ...,   1,   1,   1],
        [  2,   2,   2, ...,   2,   2,   2],
        ...,
        [ 12,  12,  12, ...,  12,  12,  12],
        [ 13,  13,  13, ...,  13,  13,  13],
        [ 14,  14,  14, ...,  14,  14,  14]],

       [[ 15,  15,  15, ...,  15,  15,  15],
        [ 16,  16,  16, ...,  16,  16,  16],
        [ 17,  17,  17, ...,  17,  17,  17],
        ...,
        [ 27,  27,  27, ...,  27,  27,  27],
        [ 28,  28,  28, ...,  28,  28,  28],
        [ 29,  29,  29, ...,  29,  29,  29]],

       [[ 30,  30,  30, ...,  30,  30,  30],
        [ 31,  31,  31, ...,  31,  31,  31],
        [ 32,  32,  32, ...,  32,  32,  32],
        ...,
        [ 42,  42,  42, ...,  42,  42,  42],
        [ 43,  43,  43, ...,  43,  43,  43],
        [ 44,  44,  44, ...,  44,  44,  44]],

       ...,

       [[105, 105, 105, ..., 105, 105, 105],
        [106, 106, 106, ..., 106, 106, 106],
        [107, 107, 107, ..., 107, 107, 107

In [231]:
a[0][0][3]

15